language: node_js
node_js:
  - "6"

install:
  - npm install -g coveralls
  - npm prune
  - npm install

script:
  - npm test

    # run tests on current master of react-apollo
  - npm link
    # XXX remove specific branch once https://github.com/apollographql/apollo-client/pull/1644 and https://github.com/apollographql/react-apollo/pull/679 are merged
  - git clone -b move-types https://github.com/apollographql/react-apollo
  - cd react-apollo && npm link apollo-client && npm i && npm test && cd ../ && rm -rf react-apollo
    # end tests of react apollo

    # run coverage and file size checks
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error
  - npm run filesize

# Allow Travis tests to run in containers.
sudo: false

notifications:
  email: false
