version: 2

jobs:
  Danger:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run: npm run danger

  Docs:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run: cd docs && npm i && npm run build

  Filesize:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run: npm run filesize

  Apollo Client:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run: npm test

  Apollo Boost:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run: npm test

  Apollo Cache:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run: npm test

  Apollo InMemory Cache:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run: npm test

  Apollo Utilities:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run: npm test

  GraphQL Anywhere:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run: npm test

  Code Coverage:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to
            # restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is
            # needed because npm ci actually removes node_modules before
            # installing to guarantee a clean slate.
            - ~/.npm
      - run:
          name: Jest suite with coverage
          command: npm run coverage --ci --testResultsProcessor=jest-junit && npm run coverage:upload
          environment:
            JEST_JUNIT_OUTPUT: "../../reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

workflows:
  version: 2
  Build and Test:
    jobs:
      - Danger
      - Docs
      - Filesize
      - Apollo Client
      - Apollo Boost
      - Apollo Cache
      - Apollo InMemory Cache
      - Apollo Utilities
      - GraphQL Anywhere
      - Code Coverage
